import { api } from '../lib/api';

/**
 * Chat service for persistent conversation memory.
 * 
 * session_id is generated by the frontend (crypto.randomUUID())
 * and stored in localStorage. It is never regenerated unless
 * the user explicitly clicks "New Chat".
 */

const SESSION_ID_KEY = 'dp_session_id';

export function getSessionId() {
  let sessionId = localStorage.getItem(SESSION_ID_KEY);
  if (!sessionId) {
    sessionId = crypto.randomUUID();
    localStorage.setItem(SESSION_ID_KEY, sessionId);
  }
  return sessionId;
}

export function regenerateSessionId() {
  const newId = crypto.randomUUID();
  localStorage.setItem(SESSION_ID_KEY, newId);
  return newId;
}

export const chatService = {
  /**
   * Send a message in the current chat session.
   */
  sendMessage: async (question, sourceId, llmConfig = {}) => {
    const sessionId = getSessionId();
    const resp = await api.chat.sendMessage({
      session_id: sessionId,
      question,
      source_id: sourceId,
      preview_only: false,
      llm_config: llmConfig,
    });
    if (resp.data?.success) {
      return resp.data.data;
    }
    throw new Error(resp.data?.message || 'Chat message failed');
  },

  /**
   * Get message history for the current session.
   */
  getHistory: async (sessionId = null) => {
    const sid = sessionId || getSessionId();
    const resp = await api.chat.getHistory(sid);
    if (resp.data?.success) {
      return resp.data.data;
    }
    return [];
  },

  /**
   * List all chat sessions.
   */
  listSessions: async () => {
    const resp = await api.chat.listSessions();
    if (resp.data?.success) {
      return resp.data.data;
    }
    return [];
  },

  /**
   * Create a new empty session with a given session_id.
   */
  newSession: async (sessionId) => {
    const resp = await api.chat.newSession({ session_id: sessionId });
    if (resp.data?.success) {
      return resp.data.data;
    }
    throw new Error(resp.data?.message || 'Failed to create new session');
  },

  /**
   * Delete a chat session.
   */
  deleteSession: async (sessionId) => {
    const resp = await api.chat.deleteSession(sessionId);
    if (resp.data?.success) {
      return true;
    }
    throw new Error(resp.data?.message || 'Failed to delete session');
  },

  /**
   * Rename a chat session.
   */
  renameSession: async (sessionId, title) => {
    const resp = await api.chat.renameSession(sessionId, title);
    if (resp.data?.success) {
      return true;
    }
    throw new Error(resp.data?.message || 'Failed to rename session');
  },
};

export default chatService;